import { describe, expect, it } from "vitest";
import { instagramRangeBoundarySeconds } from "./instagram.server";

describe("instagramRangeBoundarySeconds", () => {
  it("accepts a date-only boundary", () => {
    expect(instagramRangeBoundarySeconds("2026-08-24")).toBe(
      Date.parse("2026-08-24T00:00:00Z") / 1000,
    );
  });

  it("accepts the full ISO boundary generated by the calendar", () => {
    expect(instagramRangeBoundarySeconds("2026-08-24T03:00:00.000Z")).toBe(
      Date.parse("2026-08-24T03:00:00.000Z") / 1000,
    );
  });

  it("rejects a malformed boundary", () => {
    expect(instagramRangeBoundarySeconds("2026-08-24T03:00:00ZT00:00:00Z")).toBeNull();
  });
});
