/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CampanhasWhatsappRouteImport } from './routes/campanhas-whatsapp'
import { Route as CashbackRouteImport } from './routes/cashback'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as FluxoEnvioRouteImport } from './routes/fluxo-envio'
import { Route as Ga4RouteImport } from './routes/ga4'
import { Route as InstagramRouteImport } from './routes/instagram'
import { Route as PopupsRouteImport } from './routes/popups'
import { Route as CrmIndexRouteImport } from './routes/crm/index'
import { Route as CrmContatosRouteImport } from './routes/crm/contatos'
import { Route as CrmImportarTrayRouteImport } from './routes/crm/importar-tray'
import { Route as CrmListasEstaticasRouteImport } from './routes/crm/listas-estaticas'
import { Route as CrmLiveViewRouteImport } from './routes/crm/live-view'
import { Route as CrmSegmentosRouteImport } from './routes/crm/segmentos'
import { Route as FlowIndexRouteImport } from './routes/flow/index'
import { Route as FlowIdRouteImport } from './routes/flow/$id'
import { Route as PerformanceMetaAdsRouteImport } from './routes/performance/meta-ads'
import { Route as CrmClienteCustomerIdRouteImport } from './routes/crm/cliente/$customerId'
import { Route as CrmReguasPrimeiraSegundaRouteImport } from './routes/crm/reguas/primeira-segunda'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanhasWhatsappRoute = CampanhasWhatsappRouteImport.update({
  id: '/campanhas-whatsapp',
  path: '/campanhas-whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const CashbackRoute = CashbackRouteImport.update({
  id: '/cashback',
  path: '/cashback',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxoEnvioRoute = FluxoEnvioRouteImport.update({
  id: '/fluxo-envio',
  path: '/fluxo-envio',
  getParentRoute: () => rootRouteImport,
} as any)
const Ga4Route = Ga4RouteImport.update({
  id: '/ga4',
  path: '/ga4',
  getParentRoute: () => rootRouteImport,
} as any)
const InstagramRoute = InstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const PopupsRoute = PopupsRouteImport.update({
  id: '/popups',
  path: '/popups',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/crm/',
  path: '/crm/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmContatosRoute = CrmContatosRouteImport.update({
  id: '/crm/contatos',
  path: '/crm/contatos',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmImportarTrayRoute = CrmImportarTrayRouteImport.update({
  id: '/crm/importar-tray',
  path: '/crm/importar-tray',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmListasEstaticasRoute = CrmListasEstaticasRouteImport.update({
  id: '/crm/listas-estaticas',
  path: '/crm/listas-estaticas',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmLiveViewRoute = CrmLiveViewRouteImport.update({
  id: '/crm/live-view',
  path: '/crm/live-view',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmSegmentosRoute = CrmSegmentosRouteImport.update({
  id: '/crm/segmentos',
  path: '/crm/segmentos',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowIndexRoute = FlowIndexRouteImport.update({
  id: '/flow/',
  path: '/flow/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowIdRoute = FlowIdRouteImport.update({
  id: '/flow/$id',
  path: '/flow/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceMetaAdsRoute = PerformanceMetaAdsRouteImport.update({
  id: '/performance/meta-ads',
  path: '/performance/meta-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmClienteCustomerIdRoute = CrmClienteCustomerIdRouteImport.update({
  id: '/crm/cliente/$customerId',
  path: '/crm/cliente/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmReguasPrimeiraSegundaRoute =
  CrmReguasPrimeiraSegundaRouteImport.update({
    id: '/crm/reguas/primeira-segunda',
    path: '/crm/reguas/primeira-segunda',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/campanhas-whatsapp': typeof CampanhasWhatsappRoute
  '/cashback': typeof CashbackRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/eventos': typeof EventosRoute
  '/fluxo-envio': typeof FluxoEnvioRoute
  '/ga4': typeof Ga4Route
  '/instagram': typeof InstagramRoute
  '/popups': typeof PopupsRoute
  '/crm/contatos': typeof CrmContatosRoute
  '/crm/importar-tray': typeof CrmImportarTrayRoute
  '/crm/listas-estaticas': typeof CrmListasEstaticasRoute
  '/crm/live-view': typeof CrmLiveViewRoute
  '/crm/segmentos': typeof CrmSegmentosRoute
  '/flow/$id': typeof FlowIdRoute
  '/performance/meta-ads': typeof PerformanceMetaAdsRoute
  '/crm/': typeof CrmIndexRoute
  '/flow/': typeof FlowIndexRoute
  '/crm/cliente/$customerId': typeof CrmClienteCustomerIdRoute
  '/crm/reguas/primeira-segunda': typeof CrmReguasPrimeiraSegundaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/campanhas-whatsapp': typeof CampanhasWhatsappRoute
  '/cashback': typeof CashbackRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/eventos': typeof EventosRoute
  '/fluxo-envio': typeof FluxoEnvioRoute
  '/ga4': typeof Ga4Route
  '/instagram': typeof InstagramRoute
  '/popups': typeof PopupsRoute
  '/crm/contatos': typeof CrmContatosRoute
  '/crm/importar-tray': typeof CrmImportarTrayRoute
  '/crm/listas-estaticas': typeof CrmListasEstaticasRoute
  '/crm/live-view': typeof CrmLiveViewRoute
  '/crm/segmentos': typeof CrmSegmentosRoute
  '/flow/$id': typeof FlowIdRoute
  '/performance/meta-ads': typeof PerformanceMetaAdsRoute
  '/crm': typeof CrmIndexRoute
  '/flow': typeof FlowIndexRoute
  '/crm/cliente/$customerId': typeof CrmClienteCustomerIdRoute
  '/crm/reguas/primeira-segunda': typeof CrmReguasPrimeiraSegundaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/campanhas-whatsapp': typeof CampanhasWhatsappRoute
  '/cashback': typeof CashbackRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/eventos': typeof EventosRoute
  '/fluxo-envio': typeof FluxoEnvioRoute
  '/ga4': typeof Ga4Route
  '/instagram': typeof InstagramRoute
  '/popups': typeof PopupsRoute
  '/crm/contatos': typeof CrmContatosRoute
  '/crm/importar-tray': typeof CrmImportarTrayRoute
  '/crm/listas-estaticas': typeof CrmListasEstaticasRoute
  '/crm/live-view': typeof CrmLiveViewRoute
  '/crm/segmentos': typeof CrmSegmentosRoute
  '/flow/$id': typeof FlowIdRoute
  '/performance/meta-ads': typeof PerformanceMetaAdsRoute
  '/crm/': typeof CrmIndexRoute
  '/flow/': typeof FlowIndexRoute
  '/crm/cliente/$customerId': typeof CrmClienteCustomerIdRoute
  '/crm/reguas/primeira-segunda': typeof CrmReguasPrimeiraSegundaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/campanhas-whatsapp'
    | '/cashback'
    | '/configuracoes'
    | '/eventos'
    | '/fluxo-envio'
    | '/ga4'
    | '/instagram'
    | '/popups'
    | '/crm/contatos'
    | '/crm/importar-tray'
    | '/crm/listas-estaticas'
    | '/crm/live-view'
    | '/crm/segmentos'
    | '/flow/$id'
    | '/performance/meta-ads'
    | '/crm/'
    | '/flow/'
    | '/crm/cliente/$customerId'
    | '/crm/reguas/primeira-segunda'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/campanhas-whatsapp'
    | '/cashback'
    | '/configuracoes'
    | '/eventos'
    | '/fluxo-envio'
    | '/ga4'
    | '/instagram'
    | '/popups'
    | '/crm/contatos'
    | '/crm/importar-tray'
    | '/crm/listas-estaticas'
    | '/crm/live-view'
    | '/crm/segmentos'
    | '/flow/$id'
    | '/performance/meta-ads'
    | '/crm'
    | '/flow'
    | '/crm/cliente/$customerId'
    | '/crm/reguas/primeira-segunda'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/campanhas-whatsapp'
    | '/cashback'
    | '/configuracoes'
    | '/eventos'
    | '/fluxo-envio'
    | '/ga4'
    | '/instagram'
    | '/popups'
    | '/crm/contatos'
    | '/crm/importar-tray'
    | '/crm/listas-estaticas'
    | '/crm/live-view'
    | '/crm/segmentos'
    | '/flow/$id'
    | '/performance/meta-ads'
    | '/crm/'
    | '/flow/'
    | '/crm/cliente/$customerId'
    | '/crm/reguas/primeira-segunda'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CampanhasWhatsappRoute: typeof CampanhasWhatsappRoute
  CashbackRoute: typeof CashbackRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EventosRoute: typeof EventosRoute
  FluxoEnvioRoute: typeof FluxoEnvioRoute
  Ga4Route: typeof Ga4Route
  InstagramRoute: typeof InstagramRoute
  PopupsRoute: typeof PopupsRoute
  CrmContatosRoute: typeof CrmContatosRoute
  CrmImportarTrayRoute: typeof CrmImportarTrayRoute
  CrmListasEstaticasRoute: typeof CrmListasEstaticasRoute
  CrmLiveViewRoute: typeof CrmLiveViewRoute
  CrmSegmentosRoute: typeof CrmSegmentosRoute
  FlowIdRoute: typeof FlowIdRoute
  PerformanceMetaAdsRoute: typeof PerformanceMetaAdsRoute
  CrmIndexRoute: typeof CrmIndexRoute
  FlowIndexRoute: typeof FlowIndexRoute
  CrmClienteCustomerIdRoute: typeof CrmClienteCustomerIdRoute
  CrmReguasPrimeiraSegundaRoute: typeof CrmReguasPrimeiraSegundaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanhas-whatsapp': {
      id: '/campanhas-whatsapp'
      path: '/campanhas-whatsapp'
      fullPath: '/campanhas-whatsapp'
      preLoaderRoute: typeof CampanhasWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashback': {
      id: '/cashback'
      path: '/cashback'
      fullPath: '/cashback'
      preLoaderRoute: typeof CashbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluxo-envio': {
      id: '/fluxo-envio'
      path: '/fluxo-envio'
      fullPath: '/fluxo-envio'
      preLoaderRoute: typeof FluxoEnvioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ga4': {
      id: '/ga4'
      path: '/ga4'
      fullPath: '/ga4'
      preLoaderRoute: typeof Ga4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram': {
      id: '/instagram'
      path: '/instagram'
      fullPath: '/instagram'
      preLoaderRoute: typeof InstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/popups': {
      id: '/popups'
      path: '/popups'
      fullPath: '/popups'
      preLoaderRoute: typeof PopupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/': {
      id: '/crm/'
      path: '/crm'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/contatos': {
      id: '/crm/contatos'
      path: '/crm/contatos'
      fullPath: '/crm/contatos'
      preLoaderRoute: typeof CrmContatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/importar-tray': {
      id: '/crm/importar-tray'
      path: '/crm/importar-tray'
      fullPath: '/crm/importar-tray'
      preLoaderRoute: typeof CrmImportarTrayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/listas-estaticas': {
      id: '/crm/listas-estaticas'
      path: '/crm/listas-estaticas'
      fullPath: '/crm/listas-estaticas'
      preLoaderRoute: typeof CrmListasEstaticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/live-view': {
      id: '/crm/live-view'
      path: '/crm/live-view'
      fullPath: '/crm/live-view'
      preLoaderRoute: typeof CrmLiveViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/segmentos': {
      id: '/crm/segmentos'
      path: '/crm/segmentos'
      fullPath: '/crm/segmentos'
      preLoaderRoute: typeof CrmSegmentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow/': {
      id: '/flow/'
      path: '/flow'
      fullPath: '/flow/'
      preLoaderRoute: typeof FlowIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow/$id': {
      id: '/flow/$id'
      path: '/flow/$id'
      fullPath: '/flow/$id'
      preLoaderRoute: typeof FlowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance/meta-ads': {
      id: '/performance/meta-ads'
      path: '/performance/meta-ads'
      fullPath: '/performance/meta-ads'
      preLoaderRoute: typeof PerformanceMetaAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/cliente/$customerId': {
      id: '/crm/cliente/$customerId'
      path: '/crm/cliente/$customerId'
      fullPath: '/crm/cliente/$customerId'
      preLoaderRoute: typeof CrmClienteCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/reguas/primeira-segunda': {
      id: '/crm/reguas/primeira-segunda'
      path: '/crm/reguas/primeira-segunda'
      fullPath: '/crm/reguas/primeira-segunda'
      preLoaderRoute: typeof CrmReguasPrimeiraSegundaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CampanhasWhatsappRoute: CampanhasWhatsappRoute,
  CashbackRoute: CashbackRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EventosRoute: EventosRoute,
  FluxoEnvioRoute: FluxoEnvioRoute,
  Ga4Route: Ga4Route,
  InstagramRoute: InstagramRoute,
  PopupsRoute: PopupsRoute,
  CrmContatosRoute: CrmContatosRoute,
  CrmImportarTrayRoute: CrmImportarTrayRoute,
  CrmListasEstaticasRoute: CrmListasEstaticasRoute,
  CrmLiveViewRoute: CrmLiveViewRoute,
  CrmSegmentosRoute: CrmSegmentosRoute,
  FlowIdRoute: FlowIdRoute,
  PerformanceMetaAdsRoute: PerformanceMetaAdsRoute,
  CrmIndexRoute: CrmIndexRoute,
  FlowIndexRoute: FlowIndexRoute,
  CrmClienteCustomerIdRoute: CrmClienteCustomerIdRoute,
  CrmReguasPrimeiraSegundaRoute: CrmReguasPrimeiraSegundaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
