/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampanhasWhatsappRouteImport } from './routes/campanhas-whatsapp'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as InstagramRouteImport } from './routes/instagram'
import { Route as CrmIndexRouteImport } from './routes/crm/index'
import { Route as CrmContatosRouteImport } from './routes/crm/contatos'
import { Route as CrmListasEstaticasRouteImport } from './routes/crm/listas-estaticas'
import { Route as CrmLiveViewRouteImport } from './routes/crm/live-view'
import { Route as CrmSegmentosRouteImport } from './routes/crm/segmentos'
import { Route as PerformanceMetaAdsRouteImport } from './routes/performance/meta-ads'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanhasWhatsappRoute = CampanhasWhatsappRouteImport.update({
  id: '/campanhas-whatsapp',
  path: '/campanhas-whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const InstagramRoute = InstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/crm/',
  path: '/crm/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmContatosRoute = CrmContatosRouteImport.update({
  id: '/crm/contatos',
  path: '/crm/contatos',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmListasEstaticasRoute = CrmListasEstaticasRouteImport.update({
  id: '/crm/listas-estaticas',
  path: '/crm/listas-estaticas',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmLiveViewRoute = CrmLiveViewRouteImport.update({
  id: '/crm/live-view',
  path: '/crm/live-view',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmSegmentosRoute = CrmSegmentosRouteImport.update({
  id: '/crm/segmentos',
  path: '/crm/segmentos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceMetaAdsRoute = PerformanceMetaAdsRouteImport.update({
  id: '/performance/meta-ads',
  path: '/performance/meta-ads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campanhas-whatsapp': typeof CampanhasWhatsappRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/eventos': typeof EventosRoute
  '/instagram': typeof InstagramRoute
  '/crm/contatos': typeof CrmContatosRoute
  '/crm/listas-estaticas': typeof CrmListasEstaticasRoute
  '/crm/live-view': typeof CrmLiveViewRoute
  '/crm/segmentos': typeof CrmSegmentosRoute
  '/performance/meta-ads': typeof PerformanceMetaAdsRoute
  '/crm/': typeof CrmIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campanhas-whatsapp': typeof CampanhasWhatsappRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/eventos': typeof EventosRoute
  '/instagram': typeof InstagramRoute
  '/crm/contatos': typeof CrmContatosRoute
  '/crm/listas-estaticas': typeof CrmListasEstaticasRoute
  '/crm/live-view': typeof CrmLiveViewRoute
  '/crm/segmentos': typeof CrmSegmentosRoute
  '/performance/meta-ads': typeof PerformanceMetaAdsRoute
  '/crm': typeof CrmIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campanhas-whatsapp': typeof CampanhasWhatsappRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/eventos': typeof EventosRoute
  '/instagram': typeof InstagramRoute
  '/crm/contatos': typeof CrmContatosRoute
  '/crm/listas-estaticas': typeof CrmListasEstaticasRoute
  '/crm/live-view': typeof CrmLiveViewRoute
  '/crm/segmentos': typeof CrmSegmentosRoute
  '/performance/meta-ads': typeof PerformanceMetaAdsRoute
  '/crm/': typeof CrmIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campanhas-whatsapp'
    | '/configuracoes'
    | '/eventos'
    | '/instagram'
    | '/crm/contatos'
    | '/crm/listas-estaticas'
    | '/crm/live-view'
    | '/crm/segmentos'
    | '/performance/meta-ads'
    | '/crm/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campanhas-whatsapp'
    | '/configuracoes'
    | '/eventos'
    | '/instagram'
    | '/crm/contatos'
    | '/crm/listas-estaticas'
    | '/crm/live-view'
    | '/crm/segmentos'
    | '/performance/meta-ads'
    | '/crm'
  id:
    | '__root__'
    | '/'
    | '/campanhas-whatsapp'
    | '/configuracoes'
    | '/eventos'
    | '/instagram'
    | '/crm/contatos'
    | '/crm/listas-estaticas'
    | '/crm/live-view'
    | '/crm/segmentos'
    | '/performance/meta-ads'
    | '/crm/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampanhasWhatsappRoute: typeof CampanhasWhatsappRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EventosRoute: typeof EventosRoute
  InstagramRoute: typeof InstagramRoute
  CrmContatosRoute: typeof CrmContatosRoute
  CrmListasEstaticasRoute: typeof CrmListasEstaticasRoute
  CrmLiveViewRoute: typeof CrmLiveViewRoute
  CrmSegmentosRoute: typeof CrmSegmentosRoute
  PerformanceMetaAdsRoute: typeof PerformanceMetaAdsRoute
  CrmIndexRoute: typeof CrmIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanhas-whatsapp': {
      id: '/campanhas-whatsapp'
      path: '/campanhas-whatsapp'
      fullPath: '/campanhas-whatsapp'
      preLoaderRoute: typeof CampanhasWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram': {
      id: '/instagram'
      path: '/instagram'
      fullPath: '/instagram'
      preLoaderRoute: typeof InstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/': {
      id: '/crm/'
      path: '/crm'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/contatos': {
      id: '/crm/contatos'
      path: '/crm/contatos'
      fullPath: '/crm/contatos'
      preLoaderRoute: typeof CrmContatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/listas-estaticas': {
      id: '/crm/listas-estaticas'
      path: '/crm/listas-estaticas'
      fullPath: '/crm/listas-estaticas'
      preLoaderRoute: typeof CrmListasEstaticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/live-view': {
      id: '/crm/live-view'
      path: '/crm/live-view'
      fullPath: '/crm/live-view'
      preLoaderRoute: typeof CrmLiveViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/segmentos': {
      id: '/crm/segmentos'
      path: '/crm/segmentos'
      fullPath: '/crm/segmentos'
      preLoaderRoute: typeof CrmSegmentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance/meta-ads': {
      id: '/performance/meta-ads'
      path: '/performance/meta-ads'
      fullPath: '/performance/meta-ads'
      preLoaderRoute: typeof PerformanceMetaAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampanhasWhatsappRoute: CampanhasWhatsappRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EventosRoute: EventosRoute,
  InstagramRoute: InstagramRoute,
  CrmContatosRoute: CrmContatosRoute,
  CrmListasEstaticasRoute: CrmListasEstaticasRoute,
  CrmLiveViewRoute: CrmLiveViewRoute,
  CrmSegmentosRoute: CrmSegmentosRoute,
  PerformanceMetaAdsRoute: PerformanceMetaAdsRoute,
  CrmIndexRoute: CrmIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
